#!/bin/sh

# ========================================================================
# Copyright 2016 EUROPEAN UNION
#
# Licensed under the EUPL, Version 1.1 or - as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at: http://ec.europa.eu/idabc/eupl
# Unless required by applicable law or agreed to in writing, software distributed
# under the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the Licence for the
# specific language governing permissions and limitations under the Licence.
# Date: 01/02/2016
# Authors
# - Marco Signorini  - marco.signorini@liberaintentio.com
# - Michel Gerboles  - michel.gerboles@jrc.ec.europa.eu,
#                     European Commission - Joint Research Centre,
# - Laurent Spinelle - laurent.spinelle@jrc.ec.europa.eu,
#                     European Commission - Joint Research Centre,
#
# ========================================================================
# Backup main AirSensEUR dataset file: NOTE the tar fil will be send through
# standard file output, so it will be possible to use this script into a 
# pipe to redirect the .tar file result to a consumer

# Here is the folder destination used by this script
ASFOLDER=/usr/local/airsenseur

# Backing up database files
tar -cf - $ASFOLDER/AirSensEURDataAggregator/airsenseur.db $ASFOLDER/AirSensEURDataAggregator/*.csv $ASFOLDER/AirSensEURDataPush/history.db 


