#!/bin/sh

# ========================================================================
# Copyright 2016 EUROPEAN UNION
#
# Licensed under the EUPL, Version 1.1 or - as soon they will be approved by 
# the European Commission - subsequent versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the Licence. 
# You may obtain a copy of the Licence at: http://ec.europa.eu/idabc/eupl
# Unless required by applicable law or agreed to in writing, software distributed 
# under the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR 
# CONDITIONS OF ANY KIND, either express or implied. See the Licence for the 
# specific language governing permissions and limitations under the Licence.
# Date: 01/02/2016
# Authors
# - Marco Signorini  - marco.signorini@liberaintentio.com
# - Michel Gerboles  - michel.gerboles@jrc.ec.europa.eu,  
#                     European Commission - Joint Research Centre, 
# - Laurent Spinelle - laurent.spinelle@jrc.ec.europa.eu,
#                     European Commission - Joint Research Centre, 
# 
# ========================================================================
# Event handler for start/stop sampling process

cd "$(dirname "$0")"

SCRIPTBASE="."
SAMPLING_ENABLEFILE=$SCRIPTBASE/sampling_enabled

echo timer > /sys/class/leds/led_1/trigger

$SCRIPTBASE/check_hostdaemon
RESULT=$?
if [ "$RESULT" = 1 ]; then
        $SCRIPTBASE/stop_samplingprocess
	$SCRIPTBASE/off_gps
	$SCRIPTBASE/off_sensor
	echo SAMPLING_ENABLED=0 > $SAMPLING_ENABLEFILE
else
	$SCRIPTBASE/on_gps
	$SCRIPTBASE/on_sensor
	$SCRIPTBASE/start_samplingprocess
	echo SAMPLING_ENABLED=1 > $SAMPLING_ENABLEFILE
fi

echo none > /sys/class/leds/led_1/trigger

$SCRIPTBASE/update_leds
