#!/bin/sh

# ===========================================================================
# Copyright 2015 EUROPEAN UNION
#
# Licensed under the EUPL, Version 1.1 or subsequent versions of the
# EUPL (the "License"); You may not use this work except in compliance
# with the License. You may obtain a copy of the License at
# http://ec.europa.eu/idabc/eupl
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Date: 02/04/2015
# Authors:
# - Michel Gerboles, michel.gerboles@jrc.ec.europa.eu,
#   Laurent Spinelle, laurent.spinelle@jrc.ec.europa.eu and
#   Alexander Kotsev, alexander.kotsev@jrc.ec.europa.eu:
#                       European Commission - Joint Research Centre,
# - Marco Signorini, marco.signorini@liberaintentio.com
#
# ===========================================================================
# Restore all user services at startup

cd "$(dirname "$0")"

INTERFACE=wlan0
SCRIPTBASE="."

# WiFi Hotspot
WLAN_ENABLED=0
WLAN_ENABLEFILE=./wlan_enabled

[ -r $WLAN_ENABLEFILE ] && . $WLAN_ENABLEFILE

if [ "$WLAN_ENABLED" = 1 ]; then
        $SCRIPTBASE/event_wlan&
fi

# WiFi Client
CLWLAN_ENABLED=0
CLWLAN_ENABLEFILE=./clwlan_enabled

[ -r $CLWLAN_ENABLEFILE ] && . $CLWLAN_ENABLEFILE

if [ -f "$SCRIPTBASE/event_clwlan" ] && [ "$CLWLAN_ENABLED" = 1 ]; then
        $SCRIPTBASE/event_clwlan&
fi

