#!/bin/bash

# ===========================================================================
# Copyright 2015 EUROPEAN UNION
#
# Licensed under the EUPL, Version 1.1 or subsequent versions of the
# EUPL (the "License"); You may not use this work except in compliance
# with the License. You may obtain a copy of the License at
# http://ec.europa.eu/idabc/eupl
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Date: 02/04/2015
# Authors:
# - Michel Gerboles, michel.gerboles@jrc.ec.europa.eu, 
#   Laurent Spinelle, laurent.spinelle@jrc.ec.europa.eu and 
#   Alexander Kotsev, alexander.kotsev@jrc.ec.europa.eu:
#			European Commission - Joint Research Centre, 
# - Marco Signorini, marco.signorini@liberaintentio.com
#
# ===========================================================================

# Initializes the GPRS modem, starts a PPP connection, push updates
# then shutdown the GPRS connection and modem

SCRIPTNAME=runDataPush
PIDFILE="/var/run/$SCRIPTNAME"

exec 200>$PIDFILE
flock -n 200 || exit 1

cd "$(dirname "$0")"

SCRIPTBASE="."
CONFIGBASE="/usr/local/etc"

$SCRIPTBASE/check_datapushstatus
RESULT=$?
if [ "$RESULT" = 0 ]; then
	exit 0;
fi

# Check if we should use the GPRS channel
USEGPRS=1
USEGPRSFLAG=`grep enabled=true ${CONFIGBASE}/GPRS.properties`
if [ "$USEGPRSFLAG" = "" ]; then
	USEGPRS=0
fi

echo timer > /sys/class/leds/led_3/trigger

# If GPRS is needed, please start the PPP interface
if [ $USEGPRS = 1 ]; then
	$SCRIPTBASE/on_gprs_ppp
fi

# Push updates
cd $SCRIPTBASE/AirSensEURDataPush
java -jar AirSensEURDataPush.jar ../../etc/influxpush.properties
java -jar AirSensEURDataPush.jar ../../etc/datapushsosdb.properties
# java -jar AirSensEURDataPush.jar ../../etc/lorapush.properties
cd ..

echo none > /sys/class/leds/led_3/trigger

# If GPRS was used, stops the PPP interface
if [ $USEGPRS = 1 ]; then
	$SCRIPTBASE/off_gprs_ppp
fi

$SCRIPTBASE/update_leds

exit 1;
