/* ===========================================================================
 * Copyright 2015 EUROPEAN UNION
 *
 * Licensed under the EUPL, Version 1.1 or subsequent versions of the
 * EUPL (the "License"); You may not use this work except in compliance
 * with the License. You may obtain a copy of the License at
 * http://ec.europa.eu/idabc/eupl
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Date: 02/04/2015
 * Authors:
 * - Michel Gerboles, michel.gerboles@jrc.ec.europa.eu, 
 *   Laurent Spinelle, laurent.spinelle@jrc.ec.europa.eu and 
 *   Alexander Kotsev, alexander.kotsev@jrc.ec.europa.eu:
 *			European Commission - Joint Research Centre, 
 * - Marco Signorini, marco.signorini@liberaintentio.com
 *
 * ===========================================================================
 */

package airsenseur.dev.chemsensorpanel;

import airsenseur.dev.comm.CommProtocolHelper;
import java.util.List;

/**
 *
 * @author marco
 */
public class IIRAndAvgPanel extends javax.swing.JPanel {

    /**
     * Creates new form IIRAndAvgPanel
     */
    public IIRAndAvgPanel() {
        initComponents();
    }
    
    public void storeToBoard(int channelId) {
        
        int prescaler = sampleRatePrescaler.getRegisterSelectedValue();
        int postscaler = sampleRatePostscaler.getRegisterSelectedValue();
        int decimation = sampleRateDecimation.getRegisterSelectedValue();
        int iirDen1 = iIRDenominator1.getRegisterSelectedValue();
        int iirDen2 = iIRDenominator2.getRegisterSelectedValue();
        
        CommProtocolHelper.instance().renderSamplerPrescaler(channelId, prescaler);
        CommProtocolHelper.instance().renderSamplerPostscaler(channelId, postscaler);
        CommProtocolHelper.instance().renderSamplerDecimation(channelId, decimation);
        CommProtocolHelper.instance().renderSamplerIIRDenom(channelId, iirDen1, iirDen2);
    }
    
    public void readFromBoard(int channelId) {
        
        CommProtocolHelper.instance().renderSamplerPrescalerRead(channelId);
        CommProtocolHelper.instance().renderSamplerPostscalerRead(channelId);
        CommProtocolHelper.instance().renderSamplerDecimationRead(channelId);
        CommProtocolHelper.instance().renderSamplerIIRDenomRead(channelId);
    }
    
    public void evaluateRxMessage(CommProtocolHelper.DataMessage rxMessage, int channelId) {
        
        CommProtocolHelper helper = CommProtocolHelper.instance();
        
        Integer presc = helper.evalPrescalerInquiry(rxMessage, channelId);
        Integer posts = helper.evalPostScalerInquiry(rxMessage, channelId);
        Integer decim = helper.evalDecimationInquiry(rxMessage, channelId);
        List<Integer> iirPars = helper.evalIIRDenomInquiry(rxMessage, channelId);
        
        if (presc != null) {
            sampleRatePrescaler.setSelectedItem(presc.intValue());
            jCBPre.repaint();
        }
        
        if (posts != null) {
            sampleRatePostscaler.setSelectedItem(posts.intValue());
            jCBPost.repaint();
        }
        
        if (decim != null) {
            sampleRateDecimation.setSelectedItem(decim.intValue());
            jCBDecimation.repaint();
        }
        
        if ((iirPars != null) && (iirPars.size() == 2)){
            Integer denom1 = iirPars.get(0);
            Integer denom2 = iirPars.get(1);
            
            if (denom1 != null) {
                iIRDenominator1.setSelectedItem(denom1.intValue());
                jCBIIR1.repaint();
            }
            if (denom2 != null) {
                iIRDenominator2.setSelectedItem(denom2.intValue());
                jCBIIR2.repaint();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sampleRatePrescaler = new airsenseur.dev.chemsensorpanel.dataModel.SampleRatePrescaler();
        sampleRatePostscaler = new airsenseur.dev.chemsensorpanel.dataModel.SampleRatePostscaler();
        sampleRateDecimation = new airsenseur.dev.chemsensorpanel.dataModel.SampleRateDecimation();
        iIRDenominator1 = new airsenseur.dev.chemsensorpanel.dataModel.IIRDenominator();
        iIRDenominator2 = new airsenseur.dev.chemsensorpanel.dataModel.IIRDenominator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCBPre = new javax.swing.JComboBox();
        jCBPost = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jCBDecimation = new javax.swing.JComboBox();
        jCBIIR1 = new javax.swing.JComboBox();
        jCBIIR2 = new javax.swing.JComboBox();

        jLabel1.setText("Sample Rate Prescaler:");

        jLabel2.setText("IIR1 Coefficient:");

        jLabel3.setText("IIR2 Coefficient:");

        jLabel4.setText("Moving Average Window Size:");

        jCBPre.setModel(sampleRatePrescaler);

        jCBPost.setModel(sampleRatePostscaler);

        jLabel5.setText("Decimation Filter Size:");

        jCBDecimation.setModel(sampleRateDecimation);

        jCBIIR1.setModel(iIRDenominator1);

        jCBIIR2.setModel(iIRDenominator2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBPost, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBDecimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBIIR2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBIIR1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBPre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCBDecimation, jCBIIR1, jCBIIR2, jCBPost, jCBPre});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBIIR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBIIR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBDecimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private airsenseur.dev.chemsensorpanel.dataModel.IIRDenominator iIRDenominator1;
    private airsenseur.dev.chemsensorpanel.dataModel.IIRDenominator iIRDenominator2;
    private javax.swing.JComboBox jCBDecimation;
    private javax.swing.JComboBox jCBIIR1;
    private javax.swing.JComboBox jCBIIR2;
    private javax.swing.JComboBox jCBPost;
    private javax.swing.JComboBox jCBPre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private airsenseur.dev.chemsensorpanel.dataModel.SampleRateDecimation sampleRateDecimation;
    private airsenseur.dev.chemsensorpanel.dataModel.SampleRatePostscaler sampleRatePostscaler;
    private airsenseur.dev.chemsensorpanel.dataModel.SampleRatePrescaler sampleRatePrescaler;
    // End of variables declaration//GEN-END:variables
}
