/* ===========================================================================
 * Copyright 2015 EUROPEAN UNION
 *
 * Licensed under the EUPL, Version 1.1 or subsequent versions of the
 * EUPL (the "License"); You may not use this work except in compliance
 * with the License. You may obtain a copy of the License at
 * http://ec.europa.eu/idabc/eupl
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Date: 02/04/2015
 * Authors:
 * - Michel Gerboles, michel.gerboles@jrc.ec.europa.eu, 
 *   Laurent Spinelle, laurent.spinelle@jrc.ec.europa.eu and 
 *   Alexander Kotsev, alexander.kotsev@jrc.ec.europa.eu:
 *			European Commission - Joint Research Centre, 
 * - Marco Signorini, marco.signorini@liberaintentio.com
 *
 * ===========================================================================
 */

package airsenseur.dev.chemsensorpanel.widgets;

import airsenseur.dev.chemsensorpanel.SampleLogger;
import airsenseur.dev.comm.AppDataMessage;
import airsenseur.dev.exceptions.SensorBusException;
import java.awt.Graphics;

/**
 *
 * @author marco
 */
public class LineGraphSampleLoggerPanel extends SampleLogger {
    
    private String name = "";
    private String units = "";
    private boolean showUnits = true;
    
    /**
     * Creates new form SampleLoggerPanel
     */
    public LineGraphSampleLoggerPanel() {
        initComponents();        
    }
    
    public void disableUnits() {
        showUnits = false;
    }
    
    @Override
    public void setLoggerProperties(String title, int minVal, int maxVal, int historyLength) {
        
        lineGraph.setTitle(title);
        lineGraph.setMaxYValue(maxVal);
        lineGraph.setMaxHistory(historyLength);
    }

    @Override
    public void readFromBoard() throws SensorBusException {
        super.readFromBoard(); 
        
        // Ask for the channel name
        shieldProtocolLayer.renderSensorInquiry(boardId, sensorId);
        
        // Ask for the sensor serial number
        shieldProtocolLayer.renderReadSensorSerialNumber(boardId, sensorId);
        
        // Ask for the sensor units
        if (showUnits) {
            shieldProtocolLayer.renderReadUnits(boardId, sensorId);
        }
        
        // Ask for the sample time
        shieldProtocolLayer.renderReadSamplePeriod(boardId, sensorId);
    }
    
    
    @Override
    public void evaluateRxMessage(AppDataMessage rxMessage) {
        super.evaluateRxMessage(rxMessage);
        
        // Setup name
        String setupName = shieldProtocolLayer.evalSensorInquiry(rxMessage, boardId, sensorId);
        if ((setupName != null) && !setupName.isEmpty()) {
            name = setupName;
            String unitsToken = "";
            if (showUnits && !units.isEmpty()) {
                unitsToken = " (" + units + ")";
            }
            lineGraph.setTitle(name + unitsToken);
        }
        
        // Setup serial number
        String serialNumber = shieldProtocolLayer.evalReadSensorSerialNumber(rxMessage, boardId, sensorId);
        if ((serialNumber != null) && !serialNumber.isEmpty()) {
            lineGraph.setSubTitle(serialNumber);
        }
        
        // Units
        if (showUnits) {
            String _units = shieldProtocolLayer.evalReadUnits(rxMessage, boardId, sensorId);
            if ((_units != null) && !_units.isEmpty()) {
                units = _units;
                lineGraph.setTitle(name + " (" + units + ")");
            }
        }
        
        // Sample time
        Integer sampleTime = shieldProtocolLayer.evalReadSamplePeriod(rxMessage, boardId, sensorId);
        if (sampleTime != null) {
            jLabelOveralSampleTime.setText(sampleTime.toString());
        }
    }

    @Override
    protected double onNewSample(double sample, int timestamp) {
        sample = super.onNewSample(sample, timestamp); 
        
        lineGraph.addScore((int)sample);
        jLabelLastTimestamp.setText("" + timestamp);
        
        return sample;
    }
    
    
   @Override
   protected void paintComponent(Graphics g) {
       super.paintComponent(g);
       
       lineGraph.paintComponent(g);
   }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lineGraph = new airsenseur.dev.chemsensorpanel.widgets.LineGraphPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLastTimestamp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelOveralSampleTime = new javax.swing.JLabel();

        lineGraph.setPreferredSize(new java.awt.Dimension(296, 214));

        javax.swing.GroupLayout lineGraphLayout = new javax.swing.GroupLayout(lineGraph);
        lineGraph.setLayout(lineGraphLayout);
        lineGraphLayout.setHorizontalGroup(
            lineGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );
        lineGraphLayout.setVerticalGroup(
            lineGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jLabel1.setText("Last Sample Timestamp:");

        jLabelLastTimestamp.setText("n/a");

        jLabel2.setText("Sample Time (ms):");

        jLabelOveralSampleTime.setText("n/a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLastTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOveralSampleTime))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lineGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelLastTimestamp))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelOveralSampleTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLastTimestamp;
    private javax.swing.JLabel jLabelOveralSampleTime;
    private airsenseur.dev.chemsensorpanel.widgets.LineGraphPanel lineGraph;
    // End of variables declaration//GEN-END:variables
}
