#!/bin/sh

# ===========================================================================
# Copyright 2015 EUROPEAN UNION
#
# Licensed under the EUPL, Version 1.1 or subsequent versions of the
# EUPL (the "License"); You may not use this work except in compliance
# with the License. You may obtain a copy of the License at
# http://ec.europa.eu/idabc/eupl
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Date: 02/04/2015
# Authors:
# - Michel Gerboles, michel.gerboles@jrc.ec.europa.eu, 
#   Laurent Spinelle, laurent.spinelle@jrc.ec.europa.eu and 
#   Alexander Kotsev, alexander.kotsev@jrc.ec.europa.eu:
#			European Commission - Joint Research Centre, 
# - Marco Signorini, marco.signorini@liberaintentio.com
#
# ===========================================================================
# Battery monitor alert script.
# This script is raised by the batterymonitor daemon as soon as the battery
# voltage reaches the shutdown threshold
#
#

CONFFILE=/etc/batterymonitor/batterymonitor.conf

# Default parameters
GAUGEID=ltc2942-0
BATTERYMANAGERID=ltc4156-charger-0
ALERTVOLTAGE=3000
SHUTDOWNVOLTAGE=2900

# Don't die if stdout/stderr can't be written to
trap '' PIPE

# Read configuration parameters
if test -r ${CONFFILE} ; then
        . ${CONFFILE}
fi

DATE=`date +%Y-%m-%d:%H:%M:%S`
CHARGE=`cat /sys/class/power_supply/$GAUGEID/charge_counter`
VOLTAGE=`cat /sys/class/power_supply/$GAUGEID/voltage_now`
echo "Shut down requested by battery monitor at ${DATE} with voltage: ${VOLTAGE} and charge counter: ${CHARGE}" >> /var/log/batterymonitor.log
shutdown -h now
