#!/bin/sh
#
# Start hostapd
#

SYSLOGD_ARGS=-n
KLOGD_ARGS=-n

start() {
        printf "Starting hostapd: "
        start-stop-daemon -b -S -q -m -p /var/run/hostapd.pid --exec /usr/sbin/hostapd /etc/hostapd.conf
        echo "OK"
}

stop() {
        printf "Stopping hostapd: "
        start-stop-daemon -K -q -p /var/run/hostapd.pid
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
