#!/bin/sh

# (c) 2015 Marco Signorini 
#
#######################################################

SCRIPTBASE=/usr/local/airsenseur

# Nothing to do with this handler
if [ $1 = "1" ]; then
	/usr/bin/beep -f1000 -l80
	$SCRIPTBASE/config_wifi_ap
fi
